# Generated by Django 5.0 on 2024-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Details', '0004_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retrieval_counts',
            field=models.IntegerField(default=1),
        ),
    ]
